name=EspBaseFramework
version=1.0.0
author=Alex Waine
maintainer=alex.waine.93@gmail.com
sentence=A base framework for IoT projects for Esp8266
paragraph=A base framework that contains various functionality that can be used as a foundation to build projects on. 
category=IoT
url=https://github.com/awaine93/espBaseFramework
architectures=*
