[env:espNodemcuArduino]
platform = espressif8266
board = nodemcuv2
framework = arduino

# upload_protocol = espota
# upload_port = 192.168.1.249  ; Replace with the IP address of your ESP8266
# upload_flags =
#     --port=8266
#     --auth=blink182   ; Replace with your password
upload_port = /dev/ttyUSB0
upload_speed = 115200

board_build.filesystem = littlefs

lib_deps =
  FastLED
  ESP8266WiFi
  ESPAsyncTCP 
  DNSServer
  EEPROM
  WiFiUdp
  ArduinoOTA
  ESP8266WebServer
  https://github.com/lacamera/ESPAsyncWebServer.git
  LittleFS
  ArduinoJson
  ESP8266mDNS
  # Add any other libraries you need

monitor_speed = 115200

[env:esp-wroom-32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_port = /dev/ttyUSB0
upload_speed = 115200

board_build.filesystem = littlefs

lib_deps =
  WiFi
  WiFiClientSecure
  AsyncTCP
  DNSServer
  FastLED
  EEPROM
  WiFiUdp
  ArduinoOTA
  WebSockets
  ArduinoJson
  ESPmDNS
  https://github.com/lacamera/ESPAsyncWebServer.git
  
