[env:espNodemcuArduino]
platform = espressif8266
board = nodemcuv2
framework = arduino

upload_protocol = espota
upload_port = 192.168.1.91  ; Replace with the IP address of your ESP8266
upload_flags =
    --port=8266
    --auth=blink182   ; Replace with your password

lib_deps =
  FastLED
  ESP8266WiFi
  DNSServer
  EEPROM
  WiFiUdp
  ArduinoOTA
  ESP8266WebServer
  LittleFS
  ArduinoJson
  ESP8266mDNS
  # Add any other libraries you need

monitor_speed = 115200